sudo: false
language: python
dist: xenial

python:
  - "3.8"
  - "3.7"
  - "3.6"
  - pypy3

env:
  - # Django 3.0.x
  - DJANGO="django>=3.0,<3.1"
  # Django 2.2.x
  - DJANGO="django>=2.2,<2.3"
  # Django 2.1.x
  - DJANGO="django>=2.1,<2.2"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -e .
  - pip install flake8 coverage coveralls

before_script:
  - "flake8 uuslug"

script: coverage run --source=uuslug manage.py test

after_success:
  coveralls
