sudo: false
language: python
dist: xenial

python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "2.7"
  - pypy
  - pypy3

env:
  - DJANGO="django==3.0"
  - DJANGO="django==2.2.8"
  - DJANGO="django==1.11.26"

install:
  - pip install $DJANGO
  - pip install -r requirements.txt
  - pip install -r requirements_dev.txt
  - pip install -e .
  - pip install https://github.com/un33k/pyflakes/tarball/master
  - pip install coveralls

before_script:
  - "pycodestyle --exclude=migrations --ignore=E501,E225,E128 ."
  - if [[ $TRAVIS_PYTHON_VERSION == '2.7' ]]; then pyflakes -x W uuslug; fi

matrix:
  exclude:
    - python: "3.5"
      env: DJANGO="django==3.0"
    - python: "2.7"
      env: DJANGO="django==2.2.8"
    - python: "2.7"
      env: DJANGO="django==3.0"
    - python: pypy
      env: DJANGO="django==2.2.8"
    - python: pypy
      env: DJANGO="django==3.0"

script: coverage run --source=uuslug manage.py test

after_success: coveralls
